
- name: checkout OLS locally
  git:
    repo: '{{ backend_ols_repo }}'
    dest: '{{ backend_ols_base_dir }}'
    force: yes
    version: '{{ backend_ols_version }}'

- name: Copy config files to config directory
  copy:
    src: '{{ item }}'
    dest: '{{ backend_ols_base_dir }}/config/'
  when: (backend_ols_custom_config_files is defined) and (backend_ols_custom_config_files != "") and (backend_ols_custom_config_files is not none)
  with_items: '{{ backend_ols_custom_config_files }}'

- name: Copy config files to root directory
  copy:
    src: '{{ item }}'
    dest: '{{ backend_ols_base_dir }}/'
  when: (backend_ols_custom_config_files is defined) and (backend_ols_custom_config_files != "") and (backend_ols_custom_config_files is not none)
  with_items: '{{ backend_ols_custom_config_files }}'

- name: Copy config files to resources directory
  copy:
    src: '{{ item }}'
    dest: '{{ backend_ols_base_dir }}/ols-apps/ols-config-importer/src/main/resources/'
  when: (backend_ols_custom_config_files is defined) and (backend_ols_custom_config_files != "") and (backend_ols_custom_config_files is not none)
  with_items: '{{ backend_ols_custom_config_files }}'

- name: Copy rebranding images
  copy:
    src: '{{ item }}'
    dest: '{{ backend_ols_base_dir }}/ols-web/src/main/resources/static/img/'
  when: (backend_rebranding_images is defined) and (backend_rebranding_images != "") and (backend_rebranding_images is not none)
  with_items: '{{ backend_rebranding_images }}'

- name: Copy dockerfile of ols-config-importer
  copy:
    src: '{{ backend_importer_dockerfile }}'
    dest: '{{ backend_ols_base_dir }}/ols-apps/ols-config-importer/'
  when: (backend_importer_dockerfile is defined) and (backend_importer_dockerfile != "") and (backend_importer_dockerfile is not none)

- name: Copy dockerfile of ols-indexer
  copy:
    src: '{{ backend_indexer_dockerfile }}'
    dest: '{{ backend_ols_base_dir }}/ols-apps/ols-indexer/'
  when: (backend_indexer_dockerfile is defined) and (backend_indexer_dockerfile != "") and (backend_indexer_dockerfile is not none)

- name: Copy dockerfile of ols-web
  copy:
    src: '{{ backend_alternative_dockerfile }}'
    dest: '{{ backend_ols_base_dir }}/ols-web/'
  when: (backend_alternative_dockerfile is defined) and (backend_alternative_dockerfile != "") and (backend_alternative_dockerfile is not none)

- name: Copy dockercompose file
  copy:
    src: '{{ backend_alternative_dockercomposefile }}'
    dest: '{{ backend_ols_base_dir }}/'
  when: (backend_alternative_dockercomposefile is defined) and (backend_alternative_dockercomposefile != "") and (backend_alternative_dockercomposefile is not none)

- name: Create sitemap directory if it does not exist
  become: yes
  ansible.builtin.file:
    path: '{{ backend_ols_base_dir }}/sitemap/'
    state: directory
    mode: '0777'

- name: Copy sitemap files
  copy:
    src: '{{ item }}'
    dest: '{{ backend_ols_base_dir }}/sitemap/'
  when: (backend_sitemap_files is defined) and (backend_sitemap_files != "") and (backend_sitemap_files is not none)
  with_items: '{{ backend_sitemap_files }}'

- name: Copy token files to ols-web resources directory
  copy:
    src: '{{ item }}'
    dest: '{{ backend_ols_base_dir }}/ols-web/src/main/resources/'
  when: (backend_token_files is defined) and (backend_token_files != "") and (backend_token_files is not none)
  with_items: '{{ backend_token_files }}'
