
- name: Install ols packages
  become: yes
  package:
    name: git
    state: present
  tags:
    - root-task

- name: checkout OLS locally
  git:
    repo: '{{ backend_ols_repo }}'
    dest: '{{ backend_ols_base_dir }}'
    force: yes
    version: '{{ backend_ols_version }}'

- name: Copy config files
  copy:
    src: '{{ item }}'
    dest: '{{ backend_ols_base_dir }}/config/'
  when: (backend_ols_custom_config_files is defined) and (backend_ols_custom_config_files != "") and (backend_ols_custom_config_files is not none)
  with_items: '{{ backend_ols_custom_config_files }}'

- name: Copy rebranding images
  copy:
    src: '{{ item }}'
    dest: '{{ backend_ols_base_dir }}/ols-web/src/main/resources/static/img/'
  when: (backend_rebranding_images is defined) and (backend_rebranding_images != "") and (backend_rebranding_images is not none)
  with_items: '{{ backend_rebranding_images }}'

- name: Create docker volumes
  command: 'docker volume create --name={{ item }}'
  with_items:
    - ols-neo4j-data
    - ols-mongo-data
    - ols-solr-data
    - ols-downloads

- name: Run docker-compose up solr mongo
  command: 'docker-compose up -d solr mongo'
  args:
    chdir: '{{ backend_ols_base_dir }}'

- name: Run ols-config-importer
  command: 'docker run --net=host -v {{ backend_ols_base_dir }}/config:/config ebispot/ols-config-importer:stable'
  args:
    chdir: '{{ backend_ols_base_dir }}'

- name: Run ols-indexer
  command: 'docker run --net=host -v ols-neo4j-data:/mnt/neo4j -v ols-downloads:/mnt/downloads ebispot/ols-indexer:stable'
  args:
    chdir: '{{ backend_ols_base_dir }}'

- name: Run docker-compose up -d ols-web
  command: 'docker-compose up -d ols-web'
  args:
    chdir: '{{ backend_ols_base_dir }}'
  environment:
        LOGO: '{{ backend_logo }}'
        TITLE: '{{ backend_title }}'
        SHORT_TITLE: '{{ backend_short_title }}'
        WEB: '{{ backend_web }}'
        TWITTER: '{{ backend_twitter }}'
        ORG: '{{ backend_org }}'
        BACKGROUND_IMAGE: '{{ backend_background_image }}'
        BACKGROUND_COLOR: '{{ backend_background_color }}'
