- name: Copy public key
  copy:
    src: './tmp/id_rsa.pub'
    dest: '{{ ansible_env.HOME }}/'

- name: create authorized keys file if it doesnt exist
  shell: touch '{{ ansible_env.HOME }}/.ssh/authorized_keys'

- name: Append two blank lines to authorized keys
  shell: echo "\n" >> '{{ ansible_env.HOME }}/.ssh/authorized_keys'

- name: Append public key to authorized keys
  shell: cat '{{ ansible_env.HOME }}/id_rsa.pub' >> '{{ ansible_env.HOME }}/.ssh/authorized_keys'
