- name: Ensure NFS common is installed.
  become: yes
  apt: name=nfs-common state=present update_cache=yes
- name: Ensure rsync is installed.
  become: yes
  apt: name=rsync state=present update_cache=yes
- name: Create neo4j mount directory if it does not exist
  become: yes
  ansible.builtin.file:
     path: '{{ ansible_env.HOME }}/ts-neo4j-data'
     state: directory
     mode: '0777'
- name: Create downloads mount directory if it does not exist
  become: yes
  ansible.builtin.file:
     path: '{{ ansible_env.HOME }}/ts-downloads'
     state: directory
     mode: '0777'
- name: mount backend neo4j directory
  become: yes
  command: mount -t nfs4 '{{ backend_mongodb_ip }}:{{ ansible_env.HOME }}/ts-neo4j-data' {{ ansible_env.HOME }}/ts-neo4j-data/

- name: mount backend downloads directory
  become: yes
  command: mount -t nfs4 '{{ backend_mongodb_ip }}:{{ ansible_env.HOME }}/ts-downloads' {{ ansible_env.HOME }}/ts-downloads/

