    
- name: Creates base directory for frontend
  become: yes
  file:
    path: '{{ frontend_ols_base_dir }}'
    state: directory

- name: checkout OLS locally
  become: yes
  git:
    repo: '{{ frontend_ols_repo }}'
    dest: '{{ frontend_ols_base_dir }}'
    force: yes
    version: '{{ frontend_ols_version }}'

- name: Copy rebranding images
  become: yes
  copy:
    src: '{{ item }}'
    dest: '{{ frontend_ols_base_dir }}/ols-web/src/main/resources/static/img/'
  when: (frontend_rebranding_images is defined) and (frontend_rebranding_images != "") and (frontend_rebranding_images is not none)
  with_items: '{{ frontend_rebranding_images }}'

- name: Copy dockerfile of ols-web
  become: yes
  copy:
    src: '{{ frontend_alternative_dockerfile }}'
    dest: '{{ frontend_ols_base_dir }}/ols-web/'
  when: (frontend_alternative_dockerfile is defined) and (frontend_alternative_dockerfile != "") and (frontend_alternative_dockerfile is not none)

- name: Copy dockercompose file
  copy:
    src: '{{ frontend_alternative_dockercomposefile }}'
    dest: '{{ frontend_ols_base_dir }}/'
  when: (frontend_alternative_dockercomposefile is defined) and (frontend_alternative_dockercomposefile != "") and (frontend_alternative_dockercomposefile is not none)

- name: Recursively remove neo4j directory
  ansible.builtin.file:
    path: '{{ ansible_env.HOME }}/ts-neo4j-local-data'
    state: absent

- name: Create neo4j directory if it does not exist
  ansible.builtin.file:
    path: '{{ ansible_env.HOME }}/ts-neo4j-local-data'
    state: directory
    mode: '0777'

- name: copy nfs directory to local neo4j directory
  command: cp -R '{{ ansible_env.HOME }}/ts-neo4j-data/*' '{{ ansible_env.HOME }}/ts-neo4j-local-data/'

- name: Run docker-compose up -d ols-web
  become: yes
  command: 'docker-compose up -d ols-web'
  args:
    chdir: '{{ frontend_ols_base_dir }}'
  environment:
        MONGODB_IP: '{{ backend_mongodb_ip }}'
        LOGO: '{{ frontend_logo }}'
        TITLE: '{{ frontend_title }}'
        SHORT_TITLE: '{{ frontend_short_title }}'
        WEB: '{{ frontend_web }}'
        TWITTER: '{{ frontend_twitter }}'
        ORG: '{{ frontend_org }}'
        BACKGROUND_IMAGE: '{{ frontend_background_image }}'
        BACKGROUND_COLOR: '{{ frontend_background_color }}'
        ISSUES_PAGE: '{{ frontend_issues_page }}'
        SUPPORT_MAIL: '{{ frontend_support_mail }}'
