- name: install nfs server
  become: yes
  action: apt pkg=nfs-kernel-server state=present update_cache=yes
  tags:
    -nfs
- name: copies the exports config to the remote host
  become: yes
  copy:
     src: '{{ backend_exports_file }}'
     dest: /etc/exports
     mode: '0777'
- name: Create neo4j mount directory if it does not exist
  become: yes
  ansible.builtin.file:
     path: '{{ ansible_env.HOME }}/ts-neo4j-data'
     state: directory
     mode: '0777'
- name: Create downloads mount directory if it does not exist
  become: yes
  ansible.builtin.file:
     path: '{{ ansible_env.HOME }}/ts-downloads'
     state: directory
     mode: '0777'
- name: systemctl restart nfs-kernel-server
  become: yes
  command: systemctl restart nfs-kernel-server
